### ISSUE TITLE
Add subject_id and activity_id

### ISSUE THREAD

**Issue by olesendan** [trackerproject/trackeR#15]
Hi All.

Would it bee possible to add subject_id and activity_id when reading files and contructing TrackeRdata.

I'm thinking as extra columns to the dataframe and TrackeRdata object. Then It would be possible to identify individuel subjects or activities in and complete dataset

Greetings from Denmark
Dan Olesen

**Comment by ikosmidis** [comment]
`get_sessions(object)` where `object` is your trackeRdata object gives you session ids as set by trackeR. Is this what you are after?

By subject_id I take it you mean a way to identify different athletes in the same trackeRdata object. We have plans to add a method where the user can set those after reading the data and a method to extract session descriptions. Will that help?

In the meantime what I do is have a trackeRdata object per athlete.

**Comment by ikosmidis** [comment]
Closing this issue for now. @olesendan feel free to re-open if the above did not address your request.
