### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by AtomicNess123** [trackerproject/trackeR#26]
I have a polar watch, and would like to use this package to analyze and visualize my data.
However, I can't find how to format the data for this package to work. Is there a tutorial for beginners somewhere? Thanks.

**Comment by ikosmidis** [comment]
The best place to start is the [package's vignette](https://cran.r-project.org/web/packages/trackeR/vignettes/TourDetrackeR.html)

You can also take a look at [the full paper about the package](https://cran.r-project.org/web/packages/trackeR/vignettes/trackeR.pdf)

To get started, you'd need to extract your workouts in TCX or JSON format. Not sure how you can do it on your device, but I know others with polar watches who are doing so.
